#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("modal.Resource", IsApplication=true)]

namespace modal
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int translucent = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int translucent_black = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int alertbottomback = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int alertheaderback = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070018
			public const int btnDone = 2131165208;
			
			// aapt resource value: 0x7f070013
			public const int editColour = 2131165203;
			
			// aapt resource value: 0x7f070010
			public const int editName = 2131165200;
			
			// aapt resource value: 0x7f070016
			public const int editSmell = 2131165206;
			
			// aapt resource value: 0x7f070001
			public const int linearLayout1 = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int linearLayout2 = 2131165188;
			
			// aapt resource value: 0x7f070007
			public const int linearLayout3 = 2131165191;
			
			// aapt resource value: 0x7f07000b
			public const int linearLayout4 = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int linearLayout5 = 2131165196;
			
			// aapt resource value: 0x7f070017
			public const int linearLayout6 = 2131165207;
			
			// aapt resource value: 0x7f070000
			public const int myButton = 2131165184;
			
			// aapt resource value: 0x7f07000d
			public const int tableLayout2 = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int tableRow4 = 2131165198;
			
			// aapt resource value: 0x7f070011
			public const int tableRow5 = 2131165201;
			
			// aapt resource value: 0x7f070014
			public const int tableRow6 = 2131165204;
			
			// aapt resource value: 0x7f070002
			public const int textView1 = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int textView2 = 2131165189;
			
			// aapt resource value: 0x7f07000f
			public const int textView20 = 2131165199;
			
			// aapt resource value: 0x7f070012
			public const int textView21 = 2131165202;
			
			// aapt resource value: 0x7f070015
			public const int textView22 = 2131165205;
			
			// aapt resource value: 0x7f070008
			public const int textView3 = 2131165192;
			
			// aapt resource value: 0x7f070003
			public const int txtColor = 2131165187;
			
			// aapt resource value: 0x7f07000a
			public const int txtMessage = 2131165194;
			
			// aapt resource value: 0x7f070006
			public const int txtName = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int txtSmell = 2131165193;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ModalView = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int dialog_animation = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int lightbox_dialog = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
